"""python -m scripts.render_docs

Writes SUBMISSION.md and refreshes the results block in README.md from reports/backtest.json, so no number in either
document is typed by hand. Run after `python -m scripts.run_backtest`.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ONE_LINE = "Rift24 measures how much overnight news 24/7 rTokens have priced before the US open, and stands down when nothing's left."
assert len(ONE_LINE) <= 140, len(ONE_LINE)


def f(x, nd=2, none="n/a"):
    return none if x is None else f"{x:.{nd}f}"


def load() -> dict:
    return json.loads((ROOT / "reports" / "backtest.json").read_text(encoding="utf-8"))


def facts(j: dict) -> dict:
    st, dg, ex = j["strategies"], j["diagnostics"], j.get("exploratory")
    b, r = st["B_ALWAYS_FADE"], st["RIFT24"]
    beta = dg["priced_in_beta_large_moves"]
    out = {
        "range": j["methodology"]["date_range"], "split": j["methodology"]["split"],
        "sessions": dg["sessions_scored"], "weekends": dg["weekend_sessions_scored"], "symbol_sessions": dg["symbol_sessions_scored"],
        "beta": beta["ALL"], "beta_oos": beta["OOS"], "beta_wk": beta["weekend"],
        "gross": dg.get("always_fade_gross", {}), "sd": dg["stand_down"], "val": dg.get("data_validation", {}),
        "conv": dg.get("convergence_capture", {}),
        "B": b, "R": r, "ex": ex,
    }
    return out


def results_block(j: dict) -> str:
    x = facts(j)
    B, R, sd = x["B"], x["R"], x["sd"]
    L = [
        "<!-- RESULTS:START (generated by scripts/render_docs.py from reports/backtest.json) -->",
        f"**Window** {x['range']['first_session']} → {x['range']['last_session']} ({x['range']['calendar_days']} calendar days, {x['sessions']} sessions, "
        f"{x['weekends']} weekend voids, 10 rTokens) · **IN-SAMPLE** {x['split']['in_sample']['from']} → {x['split']['in_sample']['to']} (60 d) · "
        f"**OUT-OF-SAMPLE** {x['split']['out_of_sample']['from']} → {x['split']['out_of_sample']['to']} (30 d).",
        "",
        "| pre-specified test (decision 09:15 ET) | period | trades | Sharpe | Sortino | max DD | net bps/trade |",
        "|---|---|---|---|---|---|---|",
    ]
    for name, s in (("A DO NOTHING", None), ("B ALWAYS FADE", B), ("RIFT24 (fade, all 8 gates)", R)):
        for lab, key in (("IN-SAMPLE", "IN_SAMPLE"), ("OUT-OF-SAMPLE", "OUT_OF_SAMPLE")):
            m = s[key] if s else j["strategies"]["A_DO_NOTHING"][key]
            L.append(f"| {name if lab == 'IN-SAMPLE' else ''} | {lab} | {m['trade_count']} | {f(m['sharpe'])} | {f(m['sortino'])} | "
                     f"{f(m['max_drawdown_pct'])}% | {f(m['mean_trade_net_bps'], 1)} |")
    L += [
        "",
        f"- **H1 (fade large void moves) is rejected.** Priced-in beta at 09:15 ET = {x['beta']['beta']:.2f} "
        f"(95% CI [{x['beta']['ci95'][0]:.2f}, {x['beta']['ci95'][1]:.2f}], n = {x['beta']['n']}): the void move is already ≈ fully priced. "
        f"Always-fade earns {f(x['gross'].get('mean_gross_bps'), 1)} bps gross and {f(B['FULL']['mean_trade_net_bps'], 1)} bps net per trade.",
        f"- **Rift24 stood down on {sd['rift24_stand_down_rate_all_symbol_sessions'] * 100:.1f}% of symbol-sessions** ({sd['rift24_trades']} of {sd['symbol_sessions']} traded). "
        f"The {sd['avoided_trades_n']} trades it refused averaged {f(sd['avoided_trades_mean_net_bps'], 1)} bps net.",
        f"- Data validation: rToken 09:30 open vs Yahoo cash open, median {x['val'].get('median_bps')} bps, {x['val'].get('share_within_10_bps', 0) * 100:.1f}% within 10 bps (OBSERVED).",
    ]
    if x["ex"]:
        e = x["ex"]["strategies"]["RIFT24_RESIDUAL"]
        L.append(f"- **Exploratory, post-hoc (not a validated edge):** a two-sided residual rule at {x['ex']['selected_decision_time_et']} made {e['FULL']['trade_count']} trades - "
                 f"IN-SAMPLE Sharpe {f(e['IN_SAMPLE']['sharpe'])}, OUT-OF-SAMPLE {f(e['OUT_OF_SAMPLE']['sharpe'])} ± {f(e['OUT_OF_SAMPLE']['sharpe_se'])} "
                 f"({e['OUT_OF_SAMPLE']['trade_count']} OOS trades). Found after the null, on the same sample - see `reports/thesis.md` §6.")
    L.append("<!-- RESULTS:END -->")
    return "\n".join(L)


def update_readme(j: dict) -> None:
    p = ROOT / "README.md"
    s = p.read_text(encoding="utf-8")
    new = results_block(j)
    s2, n = re.subn(r"<!-- RESULTS:START.*?<!-- RESULTS:END -->", lambda _: new, s, flags=re.S)
    assert n == 1, "README results markers missing"
    p.write_text(s2, encoding="utf-8")


def submission(j: dict) -> str:
    x = facts(j)
    B, R, sd, ex = x["B"], x["R"], x["sd"], x["ex"]
    rows = []

    def row(metric, value, label, note=""):
        rows.append(f"| {metric} | {value} | **{label}** | {note} |")

    row("Data window", f"{x['range']['first_session']} → {x['range']['last_session']} ({x['range']['calendar_days']} d)", "OBSERVED", "Bitget spot 15m candles + Yahoo daily open/close, frozen snapshot")
    row("Sessions / weekend voids / symbol-sessions", f"{x['sessions']} / {x['weekends']} / {x['symbol_sessions']}", "OBSERVED", "10 rTokens")
    row("IN-SAMPLE / OUT-OF-SAMPLE split", "60 d / 30 d", "OBSERVED", "chronological; model refit walk-forward")
    row("Open alignment: rToken 09:30 open vs cash open", f"median {x['val'].get('median_bps')} bps; {x['val'].get('share_within_10_bps', 0) * 100:.1f}% within 10 bps", "OBSERVED", "two independent sources agree")
    row("Priced-in beta at 09:15 ET (large moves)", f"{x['beta']['beta']:.2f} [{x['beta']['ci95'][0]:.2f}, {x['beta']['ci95'][1]:.2f}], n={x['beta']['n']}", "OBSERVED", "1.00 = fully priced-in; <1 would support the fade")
    row("Always-fade gross return / trade", f"{f(x['gross'].get('mean_gross_bps'), 1)} bps (t = {f(x['gross'].get('tstat'))})", "OBSERVED", "before any cost")
    row("Round-trip fee / spread haircut", "8 bps / 4 bps", "ESTIMATED", "exchange's own published taker fee is 20 bps round trip (OBSERVED); spread history is not public")
    for nm, s in (("B ALWAYS FADE", B), ("RIFT24 (pre-specified fade)", R)):
        row(f"{nm}: Sharpe IS / OOS", f"{f(s['IN_SAMPLE']['sharpe'])} / {f(s['OUT_OF_SAMPLE']['sharpe'])}", "ESTIMATED", "net of costs; annualised √252")
        row(f"{nm}: Sortino IS / OOS", f"{f(s['IN_SAMPLE']['sortino'])} / {f(s['OUT_OF_SAMPLE']['sortino'])}", "ESTIMATED", "downside vs 0")
        row(f"{nm}: max drawdown IS / OOS", f"{f(s['IN_SAMPLE']['max_drawdown_pct'])}% / {f(s['OUT_OF_SAMPLE']['max_drawdown_pct'])}%", "ESTIMATED")
        row(f"{nm}: turnover IS / OOS", f"{f(s['IN_SAMPLE']['turnover_x_book'])}× / {f(s['OUT_OF_SAMPLE']['turnover_x_book'])}× book", "ESTIMATED")
        row(f"{nm}: trades IS / OOS, win rate", f"{s['IN_SAMPLE']['trade_count']} / {s['OUT_OF_SAMPLE']['trade_count']}, "
                                                f"{f(None if s['FULL']['win_rate'] is None else s['FULL']['win_rate'] * 100, 1)}%", "ESTIMATED")
        o = s["OOS_IS"]
        row(f"{nm}: OOS/IS Sharpe ratio", f"{f(o['ratio'])}", "ESTIMATED", o["note"])
        rs = s["FULL"]["rolling_30d_sharpe"]
        row(f"{nm}: rolling 30-day Sharpe (median [min, max])", f"{f(rs['median'])} [{f(rs['min'])}, {f(rs['max'])}] over {rs['windows']} windows", "ESTIMATED")
    row("Rift24 stand-down rate", f"{sd['rift24_stand_down_rate_all_symbol_sessions'] * 100:.1f}% of symbol-sessions ({sd['rift24_trades']} traded)", "ESTIMATED", "no residual survived 2× cost")
    row("Trades Rift24 refused that always-fade took", f"{sd['avoided_trades_n']}, mean {f(sd['avoided_trades_mean_net_bps'], 1)} bps net", "ESTIMATED")
    if ex:
        e = ex["strategies"]["RIFT24_RESIDUAL"]
        cc = ex["robustness"].get("concentration", {})
        dc = ex["robustness"]["day_clustered"]
        row(f"POST-HOC residual @ {ex['selected_decision_time_et']}: Sharpe IS / OOS (± s.e.)",
            f"{f(e['IN_SAMPLE']['sharpe'])} / {f(e['OUT_OF_SAMPLE']['sharpe'])} (±{f(e['OUT_OF_SAMPLE']['sharpe_se'])})", "ESTIMATED",
            "found after the null on the same sample; OOS not clean")
        row("POST-HOC residual: trades / distinct days / OOS trades", f"{dc['trades']} / {dc['distinct_days']} / {e['OUT_OF_SAMPLE']['trade_count']}", "ESTIMATED", "concentrated on earnings-type gap days")
        row("POST-HOC residual: return without best 3 days", f"{cc.get('total_return_pct_without_top3_days')}% (Sharpe {cc.get('sharpe_without_top3_days')})", "ESTIMATED")
    row("Forward test of the residual rule on untouched data", "harness built + pre-registered; 0 forward trades so far", "TARGETED", "first decision 22 Sep 04:00 ET; verdict stays INCONCLUSIVE until 30 trades / 15 days")
    row("Observed after-hours spreads / depth", "not collected", "TARGETED", "single fetch-time snapshot only; backtest uses +4 bps fallback")
    row("Live Bitget Signal / news-briefing event feed", "not wired", "TARGETED", "event board is fixture-driven offline")

    ex_line = ""
    if ex:
        e = ex["strategies"]["RIFT24_RESIDUAL"]
        ex_line = (f" An exploratory two-sided residual rule at {ex['selected_decision_time_et']} looks positive "
                   f"(OOS Sharpe {f(e['OUT_OF_SAMPLE']['sharpe'])} ± {f(e['OUT_OF_SAMPLE']['sharpe_se'])} on {e['OUT_OF_SAMPLE']['trade_count']} trades) but was found after the null on the same sample and is presented only as a hypothesis for a forward test.")

    return f"""# Rift24 — hackathon submission copy

Copy-paste sections for the Bitget AI Base Camp Hackathon S2 form. **Paper/backtest only. No live-money trading.**
Track: **Alpha Factory — Quantitative Strategies** · Sub-theme: **After-Hours Information Pricing**.
Every figure below is generated from `reports/backtest.json` by `python -m scripts.render_docs`; nothing is typed by hand.

---

## 1. Thesis  *(alpha source: signal / spread logic)*

U.S. cash equities are shut for about 17.5 hours overnight and 65 hours on weekends, but Bitget's rTokens trade 24/7. Information that arrives in that gap is priced by the rToken first; the cash market only prints it at the next 09:30 ET open. Rift24 measures the **void move** (rToken vs the prior cash close), asks how much of the eventual cash gap that move already contains (the **priced-in ratio**, learned only from past sessions), and computes a **residual** = model-implied cash gap − move already printed. It acts only if the expected edge is at least 2× a transparent round-trip cost (8 bps taker-style haircut + 4 bps after-hours spread haircut, both ESTIMATED), on an allow-listed rToken, while cash is closed, with data fresher than 15 minutes, capped at 20% of book per name. Otherwise the answer is **DO NOTHING** — and stand-down is part of the strategy, counted in every metric.

The pre-specified hypothesis (rTokens over-move, so fade them) is **rejected** by the data: at 09:15 ET the void move is already ≈ fully priced (β = {x['beta']['beta']:.2f}), fading earns {f(x['gross'].get('mean_gross_bps'), 1)} bps gross and {f(B['FULL']['mean_trade_net_bps'], 1)} bps net per trade, and Rift24 correctly stands down on {sd['rift24_stand_down_rate_all_symbol_sessions'] * 100:.0f}% of sessions.{ex_line}

## 2. Target user

Crypto-native Bitget retail / lower VIP traders with approximately $3k–$25k capital who hold 2–10 liquid rTokens, such as rNVDA, rTSLA, rQQQ, rSPY, rMETA, rAAPL, rMSFT, rAMZN, rGOOGL and rAMD, and who sleep through the U.S. cash session rather than running a professional stat-arb book.

## 3. Validation

Labels: **OBSERVED** = read from exchange / cash data · **ESTIMATED** = depends on a modelled assumption · **TARGETED** = not yet built or measured. Sharpe = mean/std of per-session book returns × √252 (rf 0, stand-down sessions count as 0); "n/a" means undefined, never zero.

| metric | value | label | note |
|---|---|---|---|
{chr(10).join(rows)}

## 4. Progress — exactly what is done

- [x] Session calendar (holidays, early closes, DST) cross-checked against the trading days in the real data; 10-name allow-list with verified Bitget symbols.
- [x] `DataAdapter` with a frozen-fixture adapter (offline, default) and a live adapter over Bitget public REST + Yahoo daily; loud "LIVE DATA UNAVAILABLE / FALLING BACK TO FIXTURE DATA" fallback.
- [x] Deterministic residual engine, 8 gates, walk-forward priced-in model; look-ahead protected by types and by tests that rewrite every post-decision input.
- [x] Baselines (A do-nothing, B always-fade) and Rift24 with the full metric set; reproducible `python -m scripts.run_backtest`; `reports/backtest.json` and `reports/thesis.md`.
- [x] Static desk (session clock, event board, residual table, row explanation, backtest page, weekend replay) reading pre-rendered `data/demo_state.json`.
- [x] Rule-based event→ticker mapper; optional feature-flagged LLM behind a guard.
- [x] 110+ unit/integration tests.
- [x] Pre-registered forward-test harness (`scripts/forward_test.py`, frozen sha256-stamped model, success criterion fixed in `data/forward/PREREGISTRATION.md`) — validated by replaying 21 Sep against the live API; **no forward results yet**.
- [ ] **Not done (needs you):** the required X quote post with `#BitgetHackathon` + `@Bitget_AI`, and submitting the Google Form. Both are outward-facing actions I have not taken.
- [ ] **Not done:** a GetAgent Playbook port (would require uploading to your GetAgent account), a live Bitget Signal feed, `bitget-mcp-server` wiring (the live adapter uses the same public market data over REST), observed spread history, a forward test.

## 5. Deliverables

- **Live demo:** https://rift24.vercel.app (landing page → desk / backtest / weekend replay; static, reads the same frozen fixture as the local build).
- **Source:** https://github.com/Megacollins/rift24
- Strategy code: `rift24/` (`calendar.py`, `data.py`, `residual.py`, `backtest.py`, `metrics.py`, `events.py`, `report.py`, `thesis.py`, `demo.py`).
- Backtest: `python -m scripts.run_backtest` → `reports/backtest.json`.
- Demo: `bash scripts/serve.sh` → `app/` (Desk · Backtest · Weekend replay); pre-rendered `data/demo_state.json`.
- Fixtures: `data/fixtures/` — real, frozen Bitget 15-minute candles and Yahoo daily bars (no synthetic data), plus `events.json`.
- Reports: `reports/backtest.json`, `reports/thesis.md`.
- Tests: `python -m pytest -q`.

## 6. LLM role

The LLM is limited to **event → allow-listed ticker** plus a **short explanation paragraph**, behind `RIFT24_LLM=1` (off by default; the rule-based mapper is the default). Its output is validated: unknown tickers and any text that reads like a trading instruction (buy/sell now, price targets, sizing, probabilities) are rejected and replaced by the rule-based result. The quantitative engine never imports it. The LLM does not size, time or decide any trade and is not part of the scored signal.

## 7. One-line summary  *(≤ 140 characters)*

{ONE_LINE}

*({len(ONE_LINE)} characters)*
"""


def main() -> int:
    j = load()
    (ROOT / "SUBMISSION.md").write_text(submission(j), encoding="utf-8")
    print("wrote SUBMISSION.md")
    if (ROOT / "README.md").exists():
        update_readme(j)
        print("updated README.md results block")
    return 0


if __name__ == "__main__":
    sys.exit(main())
