"""Render reports/thesis.md. Every number is read from the result objects; none is typed by hand."""
from __future__ import annotations

import datetime as dt
from pathlib import Path

from .backtest import BacktestResult
from .data import DataAdapter

NAMES = {"A_DO_NOTHING": "A DO NOTHING", "B_ALWAYS_FADE": "B ALWAYS FADE", "RIFT24": "RIFT24 (pre-specified fade)"}
HDR = ("| strategy | period | trades | return | Sharpe | Sortino | max DD | turnover | win rate | net bps / trade |\n"
       "|---|---|---|---|---|---|---|---|---|---|\n")


def _f(x, nd=2, none="n/a"):
    return none if x is None else f"{x:.{nd}f}"


def _row(m: dict) -> str:
    wr = "n/a" if m["win_rate"] is None else f"{m['win_rate'] * 100:.1f}%"
    sh = "n/a" if m["sharpe"] is None else f"{m['sharpe']:.2f} (±{_f(m['sharpe_se'])})"
    return (f"{m['trade_count']} | {_f(m['total_return_pct'])}% | {sh} | {_f(m['sortino'])} | "
            f"{_f(m['max_drawdown_pct'])}% | {_f(m['turnover_x_book'])}x | {wr} | {_f(m['mean_trade_net_bps'], 1)}")


def write_thesis(res: BacktestResult, adapter: DataAdapter, sens: list[dict], study: dict | None, path: Path) -> None:
    w, cfg, d = res.window, res.cfg, res.diagnostics
    mm, st = res.metrics, adapter.status()
    beta = d["priced_in_beta_large_moves"]
    b_all, b_oos, b_wk = beta["ALL"], beta["OOS"], beta["weekend"]
    gross = d.get("always_fade_gross", {})
    sd = d["stand_down"]
    L: list[str] = []
    add = L.append

    add("# Rift24 - thesis and findings")
    add("")
    add("> **Paper/backtest only. No live-money trading.** Generated by `python -m scripts.run_backtest`; every number below is read from the "
        "result objects, none is typed by hand. Labels: **OBSERVED** = read from exchange/cash data, **ESTIMATED** = depends on a modelled "
        "assumption (costs, spread, net-of-cost returns, implied gaps), **TARGETED** = not yet built or measured.")
    add("")
    add("## 1. The question")
    add("")
    add("U.S. cash equities close at 16:00 ET and reopen at 09:30 ET - 17.5 hours overnight and about 65 hours over a weekend. Bitget's rTokens "
        "trade 24/7 in that gap (the *void*). Information arrives during it, so the rToken prints a **void move** before the cash market has "
        "printed anything. Rift24 asks one thing: **how much of the eventual cash-market gap has the rToken already priced by the time we "
        "would have to act - and is the remainder bigger than the cost of trading it?**")
    add("")
    add("*Pre-specified hypothesis H1 (from the brief):* rTokens over-move in the void, so **fading** large void moves (`signal = -R_rtoken`) "
        "earns positive risk-adjusted returns after costs.")
    add("")
    add("## 2. Headline")
    add("")
    verdict = "rejected" if (mm["B_ALWAYS_FADE"]["FULL"]["mean_trade_net_bps"] or 0) <= 0 else "not rejected"
    add(f"1. **H1 is {verdict}** (OBSERVED prices, ESTIMATED costs). At the pre-specified 09:15 ET decision time the void move is essentially "
        f"fully priced: the cash gap equals **{b_all['beta']:.2f}x** the void move (95% CI [{b_all['ci95'][0]:.2f}, {b_all['ci95'][1]:.2f}], "
        f"n={b_all['n']} large moves; OOS {b_oos['beta']:.2f} [{b_oos['ci95'][0]:.2f}, {b_oos['ci95'][1]:.2f}]; weekends only {b_wk['beta']:.2f} "
        f"[{b_wk['ci95'][0]:.2f}, {b_wk['ci95'][1]:.2f}]). Beta at or above 1 means no over-shoot to fade.")
    add(f"2. **Always-fade loses** {abs(mm['B_ALWAYS_FADE']['FULL']['mean_trade_net_bps']):.1f} bps per trade net "
        f"(Sharpe {_f(mm['B_ALWAYS_FADE']['FULL']['sharpe'])}); before costs it earns {_f(gross.get('mean_gross_bps'), 1)} bps "
        f"(t={_f(gross.get('tstat'))}), i.e. "
        + ("indistinguishable from zero" if abs(gross.get('tstat') or 0) < 1 else "slightly negative, not positive" if (gross.get('mean_gross_bps') or 0) < 0 else "positive")
        + f" - most of the loss is the {gross.get('mean_cost_bps', 0):.0f} bps cost.")
    add(f"3. **Rift24 stands down on {sd['rift24_stand_down_rate_all_symbol_sessions'] * 100:.1f}% of symbol-sessions** "
        f"({sd['rift24_trades']} trades of {sd['symbol_sessions']}): with no over-shoot and a {cfg.rt_cost_bps + cfg.spread_fallback_bps:g} bps cost, "
        f"the gate never finds an edge worth twice the cost. It refused {sd['avoided_trades_n']} trades that always-fade took, "
        f"which averaged {_f(sd['avoided_trades_mean_net_bps'], 1)} bps net"
        + (" - here, doing nothing was the better trade." if (sd['avoided_trades_mean_net_bps'] or 0) < 0
           else " - here the refusals cost money, and that is reported, not hidden."))
    if study:
        sel = study["result"]
        rr = sel.metrics["RIFT24_RESIDUAL"]
        add(f"4. **The residual runs the other way earlier in the void (exploratory, post-hoc).** Deciding at {study['selected_decision_time']} "
            f"instead of 09:15, the cash gap is larger than the void move (beta up to {max(g['beta_large_moves']['beta'] for g in study['grid']):.2f}): rTokens "
            f"*under*-react to big overnight gaps. A two-sided residual rule made {rr['FULL']['trade_count']} trades "
            f"(OOS Sharpe {_f(rr['OOS']['sharpe'])} ± {_f(rr['OOS']['sharpe_se'])}). **This was found after the null result, on the same sample - "
            "treat it as a hypothesis, not an edge** (section 6).")
    add("")
    add("## 3. How a session is built (no look-ahead)")
    add("")
    add("```")
    add("prior cash close -- rToken trades through the void -- DECISION -- entry ---------- exit -- cash OPEN")
    add("16:00 ET (base price)                                 09:15 ET*   next bar   last pre-open bar   09:30")
    add("                                                       (* pre-specified; the exploratory study moves the decision earlier)")
    add("```")
    add("")
    add("- rToken = Bitget spot 15-minute candles (OBSERVED). Cash = Yahoo Finance daily regular-session open/close (OBSERVED). "
        "`R_rtoken` = rToken price at the decision time / rToken price at the prior cash close - 1. `R_cash` = cash open / prior cash close - 1.")
    add("- The decision function receives a `PreOpenView` that has no cash-open, entry or exit field. The priced-in model is refit **walk-forward** "
        "on sessions whose exit bar had already closed before the decision. `tests/test_no_lookahead.py` rewrites every post-decision input and asserts no decision changes.")
    add("- **Decisions, entries and exits all happen while cash is closed**: the exit is the close of the last 15-minute bar before the open, so no position is ever "
        "opened or closed in the regular session. Sessions come from a calendar with holidays, early closes and DST, cross-checked against the days Yahoo has bars for.")
    add("- **Design correction (disclosed):** the first draft exited 15 minutes *after* the open. Inspecting the weekend replay showed that bar carried regular-session price action "
        "(e.g. rMETA +348 bps in the first bar after the open on 21 Sep), which inflated the exploratory results and broke gate 1 in spirit. Exits were moved before the open, everything was "
        "recomputed, and the old exit is kept as a sensitivity row. The pre-specified H1 verdict did not change; the exploratory edge roughly halved out-of-sample.")
    add(f"- Window **{w.start} -> {w.end}** ({w.total_days} calendar days, {d['sessions_scored']} sessions, {d['weekend_sessions_scored']} weekend voids, "
        f"{len(adapter.instruments())} rTokens): **IN-SAMPLE {w.start} -> {w.is_end}** ({w.is_days} d), **OUT-OF-SAMPLE {w.is_end + dt.timedelta(days=1)} -> {w.end}** ({w.oos_days} d). "
        f"Data validation (OBSERVED): the rToken's first trade in the 09:30 bar equals Yahoo's cash open to a median of {d['data_validation']['median_bps']} bps "
        f"({d['data_validation']['share_within_10_bps'] * 100:.1f}% of {d['data_validation']['n']} sessions within 10 bps) - two unrelated sources agreeing, so the session alignment and the cash series are sound. "
        f"Mechanics: regressing the rToken's realised pre-open move on (R_cash - R_void) gives slope {d['convergence_capture']['slope']}.")
    add("")
    add("## 4. Pre-specified test: does fading work?")
    add("")
    add(HDR.rstrip("\n"))
    for s in ("A_DO_NOTHING", "B_ALWAYS_FADE", "RIFT24"):
        for key, lab in (("IS", "IN-SAMPLE"), ("OOS", "OUT-OF-SAMPLE")):
            add(f"| {NAMES[s] if key == 'IS' else ''} | {lab} | {_row(mm[s][key])} |")
    add("")
    add("*ESTIMATED: net of 8 bps round-trip + 4 bps spread haircut. Sharpe = mean/std of per-session book returns x sqrt(252), rf = 0, stand-down sessions count as 0; "
        "Sortino uses downside deviation vs 0. \"n/a\" means undefined (no trades / no variance), never zero.*")
    add("")
    for s in ("B_ALWAYS_FADE", "RIFT24"):
        o = mm[s]["OOS_IS"]
        add(f"- OOS/IS Sharpe ratio, {NAMES[s]}: {_f(o['ratio'])} - {o['note']}.")
    for s in ("B_ALWAYS_FADE", "RIFT24"):
        r = mm[s]["FULL"]["rolling_30d_sharpe"]
        pos = None if r["share_positive"] is None else r["share_positive"] * 100
        add(f"- Rolling 30-day Sharpe, {NAMES[s]}: {r['windows']} windows, min {_f(r['min'])}, median {_f(r['median'])}, max {_f(r['max'])}, positive in {_f(pos, 0)}% of windows.")
    add("")
    add("Sensitivity of always-fade (robustness only - none of these was used to pick the base configuration):")
    add("")
    add("| variant | always-fade IS Sharpe | always-fade OOS Sharpe | always-fade trades (OOS) | Rift24 trades (OOS) |")
    add("|---|---|---|---|---|")
    for r in sens:
        b, k = r["B_ALWAYS_FADE"], r["RIFT24"]
        add(f"| {r['label']} | {_f(b['IS_sharpe'])} | {_f(b['OOS_sharpe'])} | {b['trades']} ({b['OOS_trades']}) | {k['trades']} ({k['OOS_trades']}) |")
    add("")
    z = next((r for r in sens if r["label"].startswith("Costs x0")), None)
    if z:
        zi, zo = z["B_ALWAYS_FADE"]["IS_sharpe"], z["B_ALWAYS_FADE"]["OOS_sharpe"]
        same = (zi or 0) > 0 and (zo or 0) > 0
        add(f"With **zero costs** always-fade is IS {_f(zi)} / OOS {_f(zo)} Sharpe: "
            + ("positive in both periods." if same else "not positive in both periods, so there is no consistent gross edge to rescue with cheaper execution.")
            + " (That row also collapses the Gate-3 threshold to 0, so it trades every session.) "
            "The exchange's own published taker fee is 10 bps per side (OBSERVED, all 10 symbols) - worse than the 8 bps round-trip default.")
    add("")
    add("## 5. What is actually priced in")
    add("")
    add("`beta` regresses the realised cash gap on the void move, through the origin, over large moves (|R| >= 2x cost). beta < 1: the rToken over-shot (fade thesis). beta > 1: it under-shot. **OBSERVED.**")
    add("")
    add("| sample | beta | 95% CI | n |")
    add("|---|---|---|---|")
    for k, v in beta.items():
        if v:
            add(f"| {k} | {v['beta']:.2f} | [{v['ci95'][0]:.2f}, {v['ci95'][1]:.2f}] | {v['n']} |")
    add("")
    osh = d['large_move_overshoot_share']
    add(f"Large void moves over-shot the cash gap {osh * 100:.1f}% of the time, and by more than the cost {d['large_move_overshoot_beyond_cost_share'] * 100:.1f}% of the time"
        + (" - close to a coin flip with fat tails on both sides, not a bias." if 0.4 <= osh <= 0.6 else ".")
        + f" Median priced-in ratio `R_rtoken / R_cash` = {d['median_priced_in_ratio_large_moves']}.")
    add("")
    if study:
        add("### How much is priced in, and by when (post-hoc curve)")
        add("")
        add("| decision time | beta [95% CI] | always-fade net bps/trade | always-follow net bps/trade | residual trades (OOS) | residual IS Sharpe | residual OOS Sharpe |")
        add("|---|---|---|---|---|---|---|")
        for g in study["grid"]:
            b, r = g["beta_large_moves"], g["residual"]
            add(f"| {g['decision_time']} | {b['beta']:.2f} [{b['ci95'][0]:.2f}, {b['ci95'][1]:.2f}] | {_f(g['always_fade']['mean_net_bps'], 1)} | "
                f"{_f(g['always_follow']['mean_net_bps'], 1)} | {r['trades']} ({r['OOS_trades']}) | {_f(r['IS_sharpe'])} | {_f(r['OOS_sharpe'])} |")
        add("")
        fades = [g["always_fade"]["mean_net_bps"] for g in study["grid"] if g["always_fade"]["mean_net_bps"] is not None]
        betas = [g["beta_large_moves"]["beta"] for g in study["grid"]]
        add(f"Always-fade nets between {min(fades):.1f} and {max(fades):.1f} bps per trade across the {len(fades)} decision times "
            + ("- negative at every one. " if all(x < 0 for x in fades) else "- not negative at every one. ")
            + (f"Beta is above 1 at all of them ({min(betas):.2f}-{max(betas):.2f}): the cash gap extends *beyond* the void move." if all(b > 1 for b in betas)
               else "Beta is not above 1 at every decision time."))
        add("")
        add(f"## 6. Exploratory residual strategy at {study['selected_decision_time']} (POST-HOC)")
        add("")
        add(f"> {study['label']}. {study['selection_rule']}")
        add("")
        add(HDR.rstrip("\n"))
        for s, nm in (("B_ALWAYS_FADE", "B always-fade"), ("C_ALWAYS_FOLLOW", "C always-follow"), ("RIFT24_RESIDUAL", "RIFT24 residual")):
            for key, lab in (("IS", "IN-SAMPLE"), ("OOS", "OUT-OF-SAMPLE")):
                add(f"| {nm if key == 'IS' else ''} | {lab} | {_row(sel.metrics[s][key])} |")
        add("")
        o = sel.metrics["RIFT24_RESIDUAL"]["OOS_IS"]
        rb = study["robustness"]
        dc, cc = rb["day_clustered"], rb.get("concentration", {})
        sp = sel.diagnostics["side_split"]
        add(f"- OOS/IS Sharpe ratio (residual): {_f(o['ratio'])} - {o['note']}.")
        add(f"- **Concentration:** {dc['trades']} trades on only {dc['distinct_days']} distinct days (day-level mean {dc.get('day_level_mean_net_bps')} bps, t = {dc.get('day_level_tstat')}). "
            f"The best 3 days ({', '.join(cc.get('top3_days', []))}) are {(cc.get('top3_share_of_total_pnl') or 0) * 100:.0f}% of P&L; without them the strategy still returns "
            f"{cc.get('total_return_pct_without_top3_days')}% (Sharpe {cc.get('sharpe_without_top3_days')}), and {(cc.get('winning_days_share') or 0) * 100:.0f}% of trading days are winners.")
        fol = sel.metrics["C_ALWAYS_FOLLOW"]["FULL"]["mean_trade_net_bps"]
        add("- **What the trades are:** large overnight gaps (median |void| "
            f"{sorted(abs(t.void_bps) for t in sel.trades['RIFT24_RESIDUAL'])[len(sel.trades['RIFT24_RESIDUAL']) // 2] if sel.trades['RIFT24_RESIDUAL'] else 0:.0f} bps; "
            "the pattern looks like earnings-type gap days) that the thin overnight rToken book only partly prints; it keeps repricing toward the cash open before 09:30. "
            + (f"The naive always-follow earns {fol:.1f} bps net per trade at this hour; the residual gate concentrates it."
               if (fol or 0) > 0 else f"The naive always-follow earns {_f(fol, 1)} bps net per trade, so the gate is doing all of the work."))
        add("- **Cost stress:** " + "; ".join(
            f"{k}: {v['trades']} trades ({v['OOS_trades']} OOS), IS Sharpe {_f(v['IS_sharpe'])}, OOS Sharpe {_f(v['OOS_sharpe'])}"
            for k, v in rb["cost_stress"].items())
            + ". Harsher costs shrink the trade count to a handful - fewer trades rather than a collapse in quality, but far too few to conclude anything.")
        add(f"- **Side:** BUY {sp['RIFT24_RESIDUAL:BUY']['trades']} trades (mean {sp['RIFT24_RESIDUAL:BUY']['mean_net_bps']} bps), SELL/SHORT {sp['RIFT24_RESIDUAL:SELL/SHORT']['trades']} trades "
            f"(mean {sp['RIFT24_RESIDUAL:SELL/SHORT']['mean_net_bps']} bps). Spot rTokens cannot be shorted, so the short half needs a short-capable venue.")
        add("")
        add("**Why this is not a claim of edge:** it was chosen after the pre-specified test failed, on the same ~90 days and ~13 weekends; the decision time was picked from a 5-point grid "
            "(by in-sample Sharpe, but the author had already seen OOS numbers); the sample is concentrated on earnings-type days; the OOS Sharpe standard error is as large as the estimate; "
            "and a 04:00 ET entry into a thin book is not verified executable at this size. What survives is a specific, falsifiable hypothesis for a forward test.")
        add("")
    add("## 7. Why refusing to trade is the strategy")
    add("")
    add("Rift24 chooses among ADD, FADE and DO NOTHING using a signed residual: `residual = model-implied cash gap - move already printed`, judged against cost. "
        f"Binding gate at the pre-specified time: " + ", ".join(f"{k} {v}" for k, v in sd['binding_gate_counts'].items()) + f" (of {sd['symbol_sessions']} symbol-sessions). The gates are transparent: Gate 3 needs |move| >= {cfg.min_move_cost_multiple:g}x cost; "
        f"Gate 5 needs an estimated edge >= {cfg.edge_cost_multiple:g}x cost with statistical support from **past** sessions only ({cfg.min_train_obs}+ observations); with fewer, the answer is DO NOTHING, not a guess. "
        "Stand-down is counted in every metric: sessions without a trade contribute 0, and the stand-down rate is reported next to Sharpe.")
    add("")
    add("## 8. Costs and assumptions")
    add("")
    add(f"- Round-trip taker-style haircut **{cfg.rt_cost_bps:g} bps** (ESTIMATED, default from the brief; observed exchange fee is 20 bps round trip). Spread haircut **{cfg.spread_fallback_bps:g} bps** - "
        f"ESTIMATED fallback: historical bid/ask is not public, so no backtest spread is presented as observed. Extra slippage: {cfg.slippage_bps:g}. Total {cfg.rt_cost_bps + cfg.spread_fallback_bps + cfg.slippage_bps:g} bps per round trip.")
    add(f"- Sizing: equal weight over the day's trades, capped at {cfg.max_name_pct:.0%} per name, gross <= {cfg.max_gross_pct:.0%} (unlevered). Fills at the next 15-minute bar's open (entry) and the close of the last pre-open bar (exit).")
    add("- Missing data: 15-minute bars with no trades are absent (mostly weekends). Prices carry forward at most 4 bars; entry/exit bars must contain a trade or the session is excluded for every strategy. "
        f"Excluded in window: {d['excluded_symbol_sessions_in_window'] or 'none'}.")
    add(f"- Data snapshot: {st.provenance}.")
    add("")
    add("## 9. Limitations, and what would change the conclusion")
    add("")
    add("- ~90 days and ~13 weekends is a short, single-regime sample; rTokens listed on 2026-06-01. Nothing here says the null holds in other regimes.")
    add("- The void is measured against the *regular session*. U.S. pre-market (from 04:00 ET) and after-hours venues already price information, and Bitget states rToken prices are linked to U.S. exchange liquidity - "
        "consistent with beta ~ 1 by 09:15 ET. The interesting residual, if any, lives before pre-market liquidity arrives.")
    add("- Spread is assumed, not observed. Bitget-reported rToken volumes are implausibly large relative to the underlying cash markets, so volume is not used as evidence of liquidity.")
    add("- Ex-dividend gaps in the cash series are not adjusted (negligible over this window). The FADE/SELL leg needs a short-capable venue.")
    add("- **What would change the conclusion:** a forward test of the 04:00 ET residual rule on untouched data (TARGETED); observed after-hours spreads and depth (TARGETED); and more weekends.")
    add("")
    add("## 10. Reproduce")
    add("")
    add("```bash")
    add("python -m scripts.run_backtest       # prints the table, writes reports/backtest.json and this file")
    add("python -m scripts.build_demo_state   # pre-renders data/demo_state.json for the static desk")
    add("python -m pytest -q")
    add("```")
    add("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(L), encoding="utf-8")
